name: adp-env
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.7
  - numpy=1.18.*
  - scipy=1.4.*
  - scikit-image
  - pillow=7.1.*
  - scikit-learn=0.19.*
  - pandas=1.0.*
  - matplotlib=3.2.*
  - seaborn=0.10.*
  - notebook=6.0.*
  - nbconvert=5.6.*
  - tensorflow=2.0.*
  - keras=2.3.*
  - pytorch=1.5.*
  - torchvision=0.6.*
